site_name: Fred
repo_name: modxcms/fred
repo_url: https://github.com/modxcms/fred
copyright: 'Copyright &copy; 2018 MODX, LLC'
pages:
    - 'Meet Fred': index.md
    - 'Getting Started': gettingstarted.md
    - Elements:
      - Markup: elements/markup.md
      - Options: elements/options.md
      - Attributes: elements/attributes.md
    - Templates: templates/index.md
    - 'Media Sources': media_sources/index.md
    - 'System Settings': system_settings/index.md
    - Events: events/index.md
    - CMP:
        - Elements:
            - Elements: cmp/elements/elements.md
            - Categories: cmp/elements/categories.md
            - Option Sets: cmp/elements/option_sets.md
            - RTE Configs: cmp/elements/rte_configs.md
        - Blueprints:
            - Blueprints: cmp/blueprints/blueprints.md
            - Categories: cmp/blueprints/categories.md
theme:
  name: 'material'
  language: en
  palette:
      primary: 'blue'

extra:
  social:
    - type: globe
      link: https://modx.com
    - type: github-alt
      link: https://github.com/modxcms
    - type: twitter
      link: https://twitter.com/modx
    - type: facebook
      link: https://www.facebook.com/modxcms
    - type: linkedin
      link: https://linkedin.com/company/modx