site_name: Fred
repo_name: modxcms/fred
repo_url: https://github.com/modxcms/fred
copyright: 'Copyright &copy; 2018 MODX, LLC'
pages:
    - 'Meet Fred': index.md
    - 'Getting Started': gettingstarted.md
    - Elements:
      - Markup: elements/markup.md
      - Options: elements/options.md
      - Attributes: elements/attributes.md
    - Templates: templates/index.md
    - 'Media Sources': media_sources/index.md
    - 'System Settings': system_settings/index.md
    - Events: events/index.md
    - CMP:
          - Elements: cmp/elements.md
          - Element Categories: cmp/element_categories.md
          - Option Sets: cmp/option_sets.md
          - RTE Configs: cmp/rte_configs.md
          - Rebuild: cmp/rebuild.md
          - Blueprints: cmp/blueprints.md
          - Blueprint Categories: cmp/blueprint_categories.md
          - Themes: cmp/themes.md
          - Themed Templates: cmp/themed_templates.md          
theme:
  name: 'material'
  language: en
  palette:
      primary: 'blue'

extra:
  social:
    - type: globe
      link: https://modx.com
    - type: github-alt
      link: https://github.com/modxcms
    - type: twitter
      link: https://twitter.com/modx
    - type: facebook
      link: https://www.facebook.com/modxcms
    - type: linkedin
      link: https://linkedin.com/company/modx