site_name: Fred
repo_name: modxcms/fred
repo_url: https://github.com/modxcms/fred
copyright: 'Copyright &copy; 2018 <a href="https://modx.com" title="MODX">MODX</a>, LLC'

nav:
    - What is Fred?: index.md
    - Getting Started: getting_started.md
    - MODX Templates & Fred: templates.md
    - Elements: elements.md
    - Blueprints: blueprints.md
    - Fred for Developers:
      - About Developing for Fred: develop/index.md
      - Convert Exisitng Sites to Fred: develop/convert-to-fred.md
      - MODX Templates for Fred: develop/templates/index.md
      - Elements:
        - Elements: develop/elements/index.md
        - HTML Markup & Twig: develop/elements/markup.md
        - HTML Attributes: develop/elements/attributes.md
        - Options: develop/elements/options.md
        - Option Sets: develop/elements/option_sets.md
      - Blueprints: develop/blueprints/index.md
      - RTE Configs: develop/rte_configs/index.md
      - Media Sources: develop/media_sources/index.md
      - System Settings: develop/system_settings/index.md
      - Theme Creation Tutorial: develop/themes.md
      - Manager 3PC:
        - Elements: develop/cmp/elements.md
        - Element Categories: develop/cmp/element_categories.md
        - Option Sets: develop/cmp/option_sets.md
        - RTE Configs: develop/cmp/rte_configs.md
        - Rebuild: develop/cmp/rebuild.md
        - Blueprints: develop/cmp/blueprints.md
        - Blueprint Categories: develop/cmp/blueprint_categories.md
        - Building Themes: develop/cmp/themes.md
        - Themed Templates: develop/cmp/themed_templates.md
        - Media Sources: develop/cmp/media_sources.md
      - ACLs:
        - How To: develop/acls/howto.md
        - Permissions: develop/acls/permissions.md
        - Default Policies: develop/acls/policies.md
      - Events for Plugin Developers: develop/events/index.md

theme:
  name: 'material'
  language: en
  palette:
      primary: 'blue'

extra:
  social:
    - type: globe
      link: https://fred.modx.com
    - type: github-alt
      link: https://github.com/modxcms
    - type: twitter
      link: https://twitter.com/modx
    - type: facebook
      link: https://www.facebook.com/modxcms
    - type: linkedin
      link: https://linkedin.com/company/modx